### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by Naledi-Dikgale**
### In this Pull Request we did the following

- [ ] Made sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.

- [ ] Followed SOLID principles.

- [ ] Made sure that the role of  `main.rb` is only to start our code and ask the user for the initial choice of options (or to quit).

- [ ] Extracted some pieces of logic into separate classes.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @Naledi-Dikgale,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Readme file professional ✔️
- Commit messages meaningful ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I can see your app.rb file has some validation in the creation of books and co. Kindly know that all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input, not directly in the method, and by this, the principle of [SOLID](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) would be met.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Naledi-Dikgale** [comment]
Hi, @Olamarx , I don't understand the required change, can you please make it clearer so we may implement the changes.

**Comment by Olamarx** [comment]
I am sorry for not making it clearer, what I am saying is that all inputs and input validation should not be inside the create_book and other create, like rental, they should be in the main or outrightly independent of those methods.

Do you understand?

**Comment by Naledi-Dikgale** [comment]
Thank you @Olamarx

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @Naledi-Dikgale and @saluumaa,

✔️ Implementation of inputs and validation in different files.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
